services:
  django_gunicorn:
        build:
            context: .
        volumes:
            - static:/static
        env_file:
            - .env
        ports:
            - "8000:8000"

  jenkins:
      build: ./jenkins
      image: jenkins
      container_name: jenkins
      restart: always
      volumes:
        # Carpeta base de Jenkins, contiene datos sensibles.
        # Por ese motivo siempre hay que montarla en un volumen.
        - jenkins-data:/var/jenkins_home
        # La misma carpeta de Tomcat, se monta para que Jenkins pueda desplega
        # Las aplicaciones directamente
        - static:/static
      ports:
            - 8080:8080
      networks:
            - devopsnet

networks:
  devopsnet:
    driver: bridge

volumes:
  tomcat-data:
  jenkins-data:
  static:
